### ISSUE TITLE
errors publishing app

### ISSUE THREAD

**Issue by jaayb** [SanDiegoCountySheriff/RIPA#1]
I get errors about copying the antlr3 library as well as the chakra library. Tried to update the nuget packages but that seems to break the app altogether.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Copying file bin\Antlr3.Runtime.pdb to obj\Production\Package\PackageTmp\bin\Antlr3.Runtime.pdb failed. Could not find file 'bin\Antlr3.Runtime.pdb'.	RIPASTOP		0

**Comment by sremme** [comment]
Try excluding Obj folder or exclude the .pdb files from the project.
